name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake game from GitHub contributions
        id: generate_snake
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

  commit:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit generated snake game to main branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Generate Snake Game" || echo "No changes to commit"
          git push origin main
